### ISSUE TITLE
Make website title icon transparent

### ISSUE THREAD

**Issue by DavidBaldsiefen** [healthIMIS/healthIMIS-website#30]
![grafik](https://user-images.githubusercontent.com/4655486/108119584-4df65680-70a0-11eb-9a18-6137867a682b.png)

As you can see in the image above, make the white background transparent & increase the logo size accordingly. Maybe we still need some light background for contrast reasons, but that could get some "smoother" shape than a square. Just try out what looks good :)

**Comment by chThie** [comment]
I found this awesome tool: https://realfavicongenerator.net/
I'll add the generated favicons. 👍

**Comment by chThie** [comment]
Closed in 250497a410f30b44f0188dba25cec02eb0ec16ea
